name: GitHub Actions CD
on:
  push:
    branches: [master]

  workflow_dispatch:

env:
  SERVER_HOST: 31.15.19.87
  SERVER_USER: hitspatterns
  SERVER_PATH: hitspatterns
  DOTNET_VERSION: '8.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore --configuration Release

      - name: Publish Project
        run: dotnet publish -c Release -o publish

      - name: Setup SSH Key
        run: |
          set -eu
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/key"

      - name: Deploy to Server
        run: |
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" \
            --archive --compress --delete --progress --verbose \
            publish/ ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}

      - name: Restart Application
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no \
          ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "sudo systemctl restart my-dotnet-app"
